package scrapscramble.game.cards;

import scrapscramble.game.Game;
import scrapscramble.game.player.Player;

/**
 * A spell is a card with a one-time effect that's activated when it's played.
 * Spells are usually generated by other cards.
 */
public class Spell extends Card {

    /**
     * @inheritDoc
     */
    @Override
    public String toUIString(Game game, Player player) {
        return this.getName() + " - " + this.getCost() + " - Spell - " + this.getCardText();
    }
}
